### ISSUE TITLE
请问下，为什么很多个账号下载都显示网络异常呢？

### ISSUE THREAD

**Issue by DavidpYau** [BlameKidd/BaiduYunVIP#10]
有个别登录直接就异常，登录不了，有几个下载时异常，下不了，我用度盘工具下载共享地址或者转存的好像都一样

**Comment by lpg-it** [comment]
网络异常应该是此账号同时登陆人数过多造成的.
下载时异常是此账号虽然是超级会员但是仍然被限速了, 当然, 有时候也与资源有关. 但大多数是被限速了.
