### ISSUE TITLE
账号好像都已经不好用了

### ISSUE THREAD

**Issue by yzsunlight** [BlameKidd/BaiduYunVIP#13]
麻烦作者对账号进行处理，账号都不好用了
17077867608	756382ik	11月20号到期  -- 已经不是会员了
13085644899	nje1992136	2020年1月18号到期  -- 完善个人资料
16534187431	ky111111  --已经不是会员了
17068485981	520dayan88	2020年8月2号到期 -- 已经不是会员了

**Comment by lpg-it** [comment]
好的, 谢谢, 已经把之前的账号全部删除, 现在全部是最新的账号.
