### ISSUE TITLE
按下载流量计费的百度云满速下载工具

### ISSUE THREAD

**Issue by sarkrui** [BlameKidd/BaiduYunVIP#23]
### [ENFI 下载器官网](http://enfi.cloud/)
ENFI 下载器
一款通用型高速下载工具，使用 P2P 下载技术，支持 HTTP，BT，磁力链等各种协议，高速下载让你摆脱限速的困扰，从此告别低速，支持文件挂件赚下载积分。

官网说明：
当其他人下载你的做种文件时（同样的文件），你就可以获得收益，相当于你为别人提供加速下载。所以你可以将自己的本地文件拖到文件做种里来赚取积分，理论上做种文件越多，赚取的积分就越多。

- [Windows 平台](https://www.lanzous.com/b0e1gxwhe)
- [macOS 平台](https://www.lanzous.com/b0e1gxwna)

_没看清楚 Readme，作者已经添加这款下载工具了，囧。_

**Comment by Micalson** [comment]
百度云的资源如何导入下载？不好意思写错了

**Comment by sarkrui** [comment]
@Micalson 没有很明白什么是自核导入下载？是指非公开资源吗？我的经验是好像必须要公开出来的才能下载的

**Comment by Micalson** [comment]
我导入百度云的资源，显示下载失败
![图片](https://user-images.githubusercontent.com/45941423/72153637-7ca7f500-33e9-11ea-9188-a0ff1e2e1f1d.png)

**Comment by sarkrui** [comment]
@Micalson 我的经验是，有时候多尝试几次重新下载按钮可以恢复了，大概是资源下载得比较少。
