### ISSUE TITLE
建议把已经死掉的第三方下载删掉

### ISSUE THREAD

**Issue by 185264646** [BlameKidd/BaiduYunVIP#34]
由于众所周知的原因，各大第三方网盘下载客户端纷纷停止开发。一方面为了这些作者的人身安全着想，另一方面也是因为这些软件都用不了了，建议将作者明确声明停止开发的网盘下载工具撤下来。其实把整个第三方下载这一节删掉都行。

**Comment by lpg-it** [comment]
好的
