### ISSUE TITLE
B站有人盗你的账号BV1Y54y1d77C?t=34

### ISSUE THREAD

**Issue by euronx** [BlameKidd/BaiduYunVIP#38]
https://www.bilibili.com/video/BV1Y54y1d77C?t=34
删我评论是最骚的

**Comment by M0cK1nG-b1Rd** [comment]
我评论也被删了 司马营销号

**Comment by Vanilla-Yukirin** [comment]
确定是盗的吗？我随意挑了三个就一个检查出来了。也可能是打乱了顺序？

**Comment by HookAder** [comment]
看的人还不少

**Comment by lpg-it** [comment]
B站上直接复制我分享的账号多了去了，github上也有很多

**Comment by Yin-Hongwei** [comment]
B站举报没啥用，需要去申诉，这个管用 https://www.bilibili.com/v/copyright/intro
