### ISSUE TITLE
QQ群密码不知道

### ISSUE THREAD

**Issue by yi-Xu-0100** [BlameKidd/BaiduYunVIP#41]
第一个QQ群不知道密码

![image](https://user-images.githubusercontent.com/25523606/81557879-48f0d200-93bf-11ea-8544-82115d106dd9.png)

第二个QQ群搜不到

![image](https://user-images.githubusercontent.com/25523606/81557926-5c9c3880-93bf-11ea-883e-ab1c213943d3.png)

**Comment by TheFanCong** [comment]
同

**Comment by wppw0820** [comment]
同上

**Comment by lpg-it** [comment]
抱歉  自己设置错误，现在可以了
