### ISSUE TITLE
快速下载问题

### ISSUE THREAD

**Issue by Ataos** [BlameKidd/BaiduYunVIP#50]
谢谢你的帮助
我说英语，并且我正在使用翻译。
我尝试使用IDM方法进行下载，当达到错误403“禁止”的10％时，它为100kbs.
有没有新方法？
![image](https://user-images.githubusercontent.com/36573176/96731404-9c634500-138d-11eb-8a28-0f195863d196.png)

**Comment by lpg-it** [comment]
一般来说点击暂停再点击继续就可以，或者限制一下线程数
