### ISSUE TITLE
没有找到对macOS有效的方法

### ISSUE THREAD

**Issue by Barry36** [BlameKidd/BaiduYunVIP#51]
非常感谢大神的分享🙏
在您推荐的三个方法中，我没有找到可以适用于macOS的方法，想请教您如果用macOS百度网盘下载的话，可以提速吗？谢谢！

**Comment by lpg-it** [comment]
这个。。。因为我没有mac电脑 所以也没有办法进行测试，如果可以，尽量使用低版本百度网盘进行登录。
