### ISSUE TITLE
BND2,WIN10 无法选择微博登陆，无法选择第三方方式登陆

### ISSUE THREAD

**Issue by WAllen2019** [BlameKidd/BaiduYunVIP#7]
BND2,WIN10 无法选择微博登陆，无法选择第三方方式登陆，win10版本号：1903,(18362.418)

**Comment by lpg-it** [comment]
下载工具出现问题, 本人也无能为力啊, 只是收集一些目前比较好的工具供临时下载用.
直接用账号登录百度网盘下载就可以.
